name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
      placeholder: "Describe the feature..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
      placeholder: "Explain the use case and benefits..."
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Suggested Implementation
      description: Optional - how you might implement this
      placeholder: "Any ideas on implementation..."

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information (links, examples, etc.)
