name: Python Testing & Linting

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'tools/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'tools/**/*.py'
      - 'tests/**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black pytest pytest-cov

    - name: Check code formatting with black
      run: |
        black --check tools/ tests/ || true

    - name: Lint with pylint
      run: |
        pylint tools/**/*.py tests/**/*.py || true
      continue-on-error: true

    - name: Check syntax
      run: |
        find tools/ tests/ -name '*.py' -exec python -m py_compile {} \;

    - name: Run scanner tests
      run: |
        python -m pytest tests/test_scanner.py -v --tb=short

    - name: Run GUI tests (headless)
      run: |
        xvfb-run python -m pytest tests/test_gui.py -v --tb=short || true
      continue-on-error: true

    - name: Run all tests with coverage
      run: |
        python -m pytest tests/ -v --cov=tools --cov-report=term --cov-report=html
      continue-on-error: true

    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      if: matrix.python-version == '3.11'
      with:
        name: coverage-report
        path: htmlcov/

