name: Shell Script Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'scripts/**'
      - 'start.sh'
      - '.github/workflows/shell.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'scripts/**'
      - 'start.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install shellcheck
      run: sudo apt-get install -y shellcheck

    - name: Run shellcheck on scripts
      run: |
        shellcheck scripts/*.sh start.sh || true
      continue-on-error: true

    - name: Check bash syntax
      run: |
        for script in scripts/*.sh start.sh; do
          echo "Checking syntax of $script..."
          bash -n "$script" || exit 1
        done

    - name: Validate script shebangs
      run: |
        for script in scripts/*.sh start.sh; do
          if [[ -f "$script" ]]; then
            if ! head -1 "$script" | grep -q "^#!/usr/bin/env bash"; then
              echo "Warning: $script doesn't have proper shebang"
            fi
          fi
        done
